import './globals.css';
import type { Metadata } from 'next';
import { Inter, Roboto_Mono } from 'next/font/google';
import NavMenu from './NavMenu';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
    weight: ['100', '400', '700', '900'],
    // weight: ['thin', 'normal', 'bold', 'black'],
});

const roboto_mono = Roboto_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
    weight: ['100', '400', '700'],
    // weight: ['thin', 'normal', 'bold'],
});

export const metadata: Metadata = {
    title: 'NextSpace',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={roboto_mono.className}>
                <NavMenu />
                {children}
            </body>
        </html>
    );
}
